spring:
  application:
    name: project

  datasource:
    url: jdbc:postgresql://localhost:5432/one_dream_us
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret-key: UOOvqsvHKLKOy2vYkDjuJVfLqpwcJm1ds34DOiSI5nE=

#logging:
#  level:
#   root: TRACE