spring:
  application:
    name: project

  datasource:
    url: jdbc:postgresql://localhost:5432/one_dream_us
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true